# MediaWiki with MariaDB
#
# Access via "http://localhost:8877"
#   (or "http://$(docker-machine ip):8877" if using docker-machine)

services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile-ci
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--show-error", "--fail", "http://127.0.0.1/"]
      interval: 2s
      timeout: 5s
      retries: 60
      start_period: 10s
    environment:
      MYSQL_SERVER: database
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
    ports:
      - 8877:80
    links:
      - database
    volumes:
      - /var/www/html/images
      - ./build:/dc-scripts

  database:
    image: mariadb:10.11
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mariadb --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --database=$$MYSQL_DATABASE --silent --skip-column-names -e \"SELECT @@global.read_only = 0\" | grep -q 1"]
      interval: 2s
      timeout: 5s
      retries: 120
      start_period: 15s
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
